```yaml
# Column mappings for ADNKS dataset
columns:
  nuts1: NUTS1KODU
  nuts2: NUTS2KODU
  nuts3: NUTS3KODU
  province: IL
  district: ILCE
  status: ILCE STATU
  population: NUFUS2023
  neighborhood_code: MAH_KOY_KODU

# Special population adjustments
special_adjustments:
  - stratum: TR61  # Adjusted to TR61 to match group assignment
    condition: IL == 'Isparta' and ILCE == 'Merkez' and STATU_CAT == 'M&D'
    action: add_population
  - stratum: TRC13
    condition: IL == 'Adıyaman' and ILCE == 'Merkez' and STATU_CAT == 'M&D'
    action: add_population
```